"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tNum: (num: number | string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'Dashboards': 'Dashboards',
    'Implementation Corner': 'Classroom Implementation',
    'Classroom Implementation': 'Classroom Implementation',
    'Back to Classroom Implementation': 'Back to Classroom Implementation',
    'Students': 'Students',
    'Upload': 'Upload',
    'Users': 'Users',
    'Data': 'Data',
    'Logins': 'Logins',
    'Record Score': 'Record Score',
    'Sign In': 'Sign In',
    'Sign Out': 'Sign Out',
    // Dashboard
    'FLN Impact Dashboard': 'FLN Impact Dashboard',
    'Real-time state and division progress tracking towards NIPUN Bharat Mission targets.': 'Real-time state and division progress tracking towards NIPUN Bharat Mission targets.',
    'Select Division': 'Select Division',
    'Select Project Office': 'Select Project Office',
    'Select School': 'Select School',
    'NIPUN Bharat Mission': 'NIPUN Bharat Mission',
    'The NIPUN Bharat Mission targets 100% foundational literacy and numeracy proficiency for all grade-level students. We monitor student progress through targeted baseline and endline assessments to bridge the learning gap.': 'The NIPUN Bharat Mission targets 100% foundational literacy and numeracy proficiency for all grade-level students. We monitor student progress through targeted baseline and endline assessments to bridge the learning gap.',
    'Literacy (L4 Story Reading)': 'Literacy (L4 Story Reading)',
    'Numeracy (L3 Division)': 'Numeracy (L3 Division)',
    'Current Level': 'Current Level',
    'Target': 'Target',
    'Total Assessments': 'Total Assessments',
    'Total Students': 'Total Students',
    'Arena Engagement': 'Arena Engagement',
    'Single Games': 'Single Games',
    'Target Tracking': 'Target Tracking',
    'Growth Velocity': 'Growth Velocity',
    'Engagement Metrics': 'Engagement Metrics',
    'Pedagogy Coverage': 'Pedagogy Coverage',
    'Division Rank': 'Division Rank',
    'P.O. Rank': 'P.O. Rank',
    'Project Office Leaderboard (Endline Only)': 'Project Office Leaderboard (Endline Only)',
    'Ranking based on student story reading and subtraction mastery rates in Endline assessments.': 'Ranking based on student story reading and subtraction mastery rates in Endline assessments.',
    'Top Performer': 'Top Performer',
    'Project Office': 'Project Office',
    'Efficiency Score': 'Efficiency Score',
    'Story Reading': 'Story Reading',
    'Subtraction Mastery': 'Subtraction Mastery',
    'Assessed': 'Assessed',
    'No ranking data available for selected filters.': 'No ranking data available for selected filters.',
    'Division': 'Division',
    'Proficiency': 'Proficiency',
    'Assessments': 'Assessments',
    'Status': 'Status',
    'Growth Over Time': 'Growth Over Time',
    'Progress timeline showing baseline vs midline vs endline outcomes.': 'Progress timeline showing baseline vs midline vs endline outcomes.',
    'All Divisions': 'All Divisions',
    'All Project Offices': 'All Project Offices',
    'All Schools': 'All Schools',
    'All Terms': 'All Terms',
    'Filters': 'Filters',
    'Detailed Breakdown': 'Detailed Breakdown',
    'Level': 'Level',
    'Showing page': 'Showing page',
    'of': 'of',
    'records': 'records',
    // Students / Roster
    'Search student...': 'Search student...',
    'Class': 'Class',
    'Gender': 'Gender',
    'Age': 'Age',
    'School': 'School',
    'Actions': 'Actions',
    'Add Student': 'Add Student',
    'No students found.': 'No students found.',
    'Active Students': 'Active Students',
    'List of all registered students and their status.': 'List of all registered students and their status.',
    'Female': 'Female',
    'Male': 'Male',
    // Resources
    'Interactive Simulations': 'FLN Games',
    'Hands-on simulations, games and learning pathways to master FLN concepts.': 'Hands-on simulations, games and learning pathways to master FLN concepts.',
    'Session Planner': 'Session Planner',
    'Pedagogy Videos': 'Pedagogy Videos',
    'Articles': 'TaRL Help Manuals',
    'Holistic development manuals': 'Holistic development manuals',
    'TLM Guide': 'TLM Guide',
    'Maximize Learning with TLM': 'Maximize Learning with TLM',
    'Read TLM Manual': 'Read TLM Manual',
    'TLM Support Videos': 'TLM Support Videos',
    'Filter by Subject': 'Filter by Subject',
    'All Subjects': 'All Subjects',
    'Language': 'Language',
    'Maths': 'Maths',
    'Play Game': 'Play Game',
    'Start Competition': 'Start Competition',
    // Levels
    'Beginner': 'Beginner',
    'Letter': 'Letter',
    'Word': 'Word',
    'Paragraph': 'Paragraph',
    'Story': 'Story',
    'Num 1-9': 'Num 1-9',
    'Num 10-99': 'Num 10-99',
    'Addition': 'Addition',
    'Subtraction': 'Subtraction',
    'Math Division': 'Division',
    // Student Profile / Report Card
    'FLN Child Progress Report Card': 'FLN Child Progress Report Card',
    'Practice Games': 'Practice Games',
    'Arena Battles': 'Arena Battles',
    'Total Learning Playtime': 'Total Learning Playtime',
    'Recommended TaRL Activities': 'Recommended TaRL Activities',
    'Literacy Focus': 'Literacy Focus',
    'Numeracy Focus': 'Numeracy Focus',
    'Assessment Audit Trail': 'Assessment Audit Trail',
    'Reliability Feed': 'Reliability Feed',
    'Practice Records': 'Practice Records',
    'Opponent': 'Opponent',
    'Result': 'Result',
    'Score': 'Score',
    'Time': 'Time',
    'Draw': 'Draw',
    'Won 🏆': 'Won 🏆',
    'Lost': 'Lost',
    'No practice sessions logged yet.': 'No practice sessions logged yet.',
    'No arena battles played yet.': 'No arena battles played yet.',
    'Test Now': 'Test Now',
    'Back to Directory': 'Back to Directory',
    'Student not found.': 'Student not found.',
    'No Assessments Yet': 'No Assessments Yet',
    'Test this student to generate personalized TaRL curriculum recommendations.': 'Test this student to generate personalized TaRL curriculum recommendations.',
    'Literacy': 'Literacy',
    'Numeracy': 'Numeracy',
    'No specific activities mapped for this level yet.': 'No specific activities mapped for this level yet.',
    // Game Simulations
    'Math Duel (वजाबाकी आणि भागाकार)': 'Math Duel (Subtraction & Division)',
    'Quickly solve the math problem! Speed is key to winning the point.': 'Quickly solve the math problem! Speed is key to winning the point.',
    'Number Race (सर्वात मोठी संख्या)': 'Number Race (Find Largest Number)',
    'Find the LARGEST number before your opponent does! Be the fastest to score.': 'Find the LARGEST number before your opponent does! Be the fastest to score.',
    'Place Value Battle (शतक-दशक-एकक)': 'Place Value Battle (H-T-O)',
    'Identify the total number from the H-T-O representation! First correct tap wins.': 'Identify the total number from the H-T-O representation! First correct tap wins.',
    'Tili Bundle Duel': 'Tili Bundle Duel',
    'Make the number using bundles and sticks!': 'Make the number using bundles and sticks!',
    'Bundles (Tens)': 'Bundles (Tens)',
    'Sticks (Ones)': 'Sticks (Ones)',
    '+ Bundle': '+ Bundle',
    '+ Stick': '+ Stick',
    'Make the Number': 'Make the Number',
    'Tens': 'Tens',
    'Ones': 'Ones',
    // Student Leaderboard
    'Student Leaderboard': 'Student Leaderboard',
    'Performance Score': 'Performance Score',
    'FLN Level Score': 'FLN Level Score',
    'Engagement Score': 'Engagement Score',
    'Victory Bonus': 'Victory Bonus',
    'Games Played': 'Games Played',
    'Victories': 'Victories',
    'Best Performing Students': 'Best Performing Students',
    'Based on FLN levels, game participation, and battle victories': 'Based on FLN levels, game participation, and battle victories',
    'No students found matching current filters.': 'No students found matching current filters.',
    // TaRL Activities - Literacy
    'Sound Bingo': 'Sound Bingo',
    'Teacher says a letter sound, and students find objects in the room starting with that sound. The first to find 3 wins.': 'Teacher says a letter sound, and students find objects in the room starting with that sound. The first to find 3 wins.',
    'Objects in classroom': 'Objects in classroom',
    'Pebbles as markers': 'Pebbles as markers',
    'Air Drawing': 'Air Drawing',
    'Draw letters in the air using large arm movements. Have students repeat the letter\'s sound while drawing to build muscle memory.': 'Draw letters in the air using large arm movements. Have students repeat the letter\'s sound while drawing to build muscle memory.',
    'None': 'None',
    'Mind-Mapping Objects': 'Mind-Mapping Objects',
    'Write a letter in the center of a chalkboard. Draw branches for every object students can name that starts with that letter.': 'Write a letter in the center of a chalkboard. Draw branches for every object students can name that starts with that letter.',
    'Chalk': 'Chalk',
    'Blackboard': 'Blackboard',
    'Letter Sand-Trays': 'Letter Sand-Trays',
    'Provide shallow trays of sand or dirt. Have students trace letters they recognize. This tactile feedback is essential for recall.': 'Provide shallow trays of sand or dirt. Have students trace letters they recognize. This tactile feedback is essential for recall.',
    'Sand/Dirt': 'Sand/Dirt',
    'Shallow trays': 'Shallow trays',
    'Read-Around-the-Circle': 'Read-Around-the-Circle',
    'Sit in a circle. Each student reads one basic word from a flashcard. If they get it right, they stay in; otherwise, they get a \'bonus\' word.': 'Sit in a circle. Each student reads one basic word from a flashcard. If they get it right, they stay in; otherwise, they get a \'bonus\' word.',
    'Word Flashcards': 'Word Flashcards',
    'Word Building Blocks': 'Word Building Blocks',
    'Use individual letter tiles (C-A-T). Have students physically move tiles to form new words like B-A-T or M-A-T.': 'Use individual letter tiles (C-A-T). Have students physically move tiles to form new words like B-A-T or M-A-T.',
    'Letter tiles': 'Letter tiles',
    'Stop-and-Predict': 'Stop-and-Predict',
    'Read a paragraph aloud. Stop halfway and ask the student what they think will happen next to build active comprehension.': 'Read a paragraph aloud. Stop halfway and ask the student what they think will happen next to build active comprehension.',
    'Storybooks': 'Storybooks',
    'Paragraph cards': 'Paragraph cards',
    'Sentence Jumble': 'Sentence Jumble',
    'Write sentences from a paragraph on separate strips. Have the student arrange them in the correct sequential order.': 'Write sentences from a paragraph on separate strips. Have the student arrange them in the correct sequential order.',
    'Paper strips': 'Paper strips',
    'Scissors': 'Scissors',
    'Moral Summaries': 'Moral Summaries',
    'After reading a story, ask the student to write one \'moral\' or lesson they learned in their own words.': 'After reading a story, ask the student to write one \'moral\' or lesson they learned in their own words.',
    'Notebook': 'Notebook',
    'Pencil': 'Pencil',
    'Roleplay Theater': 'Roleplay Theater',
    'Choose a story character and have the student act out their favorite scene. This deepens emotional connection to the text.': 'Choose a story character and have the student act out their favorite scene. This deepens emotional connection to the text.',
    'Basic props': 'Basic props',
    // TaRL Activities - Numeracy
    'Number Songs': 'Number Songs',
    'Sing \'Five Little Ducks\' or similar counting songs while using fingers to physically subtract numbers.': 'Sing \'Five Little Ducks\' or similar counting songs while using fingers to physically subtract numbers.',
    'Rock Counting': 'Rock Counting',
    'Gather 10 stones. Count them one by one, moving them from a \'pile\' to a \'line\'. Ask \'How many now?\' frequently.': 'Gather 10 stones. Count them one by one, moving them from a \'pile\' to a \'line\'. Ask \'How many now?\' frequently.',
    'Stones/Seeds': 'Stones/Seeds',
    'Dot Matching': 'Dot Matching',
    'On a sheet of paper, draw groups of dots next to numbers. Have the student draw lines connecting the correct pairs.': 'On a sheet of paper, draw groups of dots next to numbers. Have the student draw lines connecting the correct pairs.',
    'Paper': 'Paper',
    'Marker': 'Marker',
    'Flashcard Hopscotch': 'Flashcard Hopscotch',
    'Draw hopscotch grids with numbers 1-9. The child must say the number aloud before jumping into the square.': 'Draw hopscotch grids with numbers 1-9. The child must say the number aloud before jumping into the square.',
    'Outdoor space': 'Outdoor space',
    'Bundle Races': 'Bundle Races',
    'Give students 30 sticks. Whoever ties them into 3 bundles of 10 the fastest wins. Teaches the concept of \'tens\'.': 'Give students 30 sticks. Whoever ties them into 3 bundles of 10 the fastest wins. Teaches the concept of \'tens\'.',
    'Sticks/Straws': 'Sticks/Straws',
    'Rubber bands': 'Rubber bands',
    'Place Value Grids': 'Place Value Grids',
    'Use an abacus or a drawn H-T-U (Hundreds, Tens, Units) grid. Have students place pebbles in each column to represent 562.': 'Use an abacus or a drawn H-T-U (Hundreds, Tens, Units) grid. Have students place pebbles in each column to represent 562.',
    'H-T-U Grid': 'H-T-U Grid',
    'Pebbles': 'Pebbles',
    'Carry-over Grids': 'Carry-over Grids',
    'Use a color-coded carry-over grid. When adding 9+5, show how the \'1\' jumps into the Tens column visually.': 'Use a color-coded carry-over grid. When adding 9+5, show how the \'1\' jumps into the Tens column visually.',
    'Color markers': 'Color markers',
    'Grid paper': 'Grid paper',
    'Borrowing Roleplay': 'Borrowing Roleplay',
    'Roleplay \'Borrowing a Bundle\'. If I have 2 bundles and 3 sticks, and I need to give away 5, I must \'untie\' one bundle.': 'Roleplay \'Borrowing a Bundle\'. If I have 2 bundles and 3 sticks, and I need to give away 5, I must \'untie\' one bundle.',
    'Bundles of 10': 'Bundles of 10',
    'Loose sticks': 'Loose sticks',
    'Fair Share Picnic': 'Fair Share Picnic',
    'Give a student 20 seeds and 4 friends. Ask them to distribute the seeds \'fairly\' so everyone has an equal amount.': 'Give a student 20 seeds and 4 friends. Ask them to distribute the seeds \'fairly\' so everyone has an equal amount.',
    'Seeds': 'Seeds',
    'Plates/Cups': 'Plates/Cups',
    // Implementation Tracker
    'Implementation Tracker': 'Implementation Tracker',
    'Track school-wise 90-minute cycle implementation and activity completion.': 'Track school-wise 90-minute cycle implementation and activity completion.',
    '7 Days': '7 Days',
    '30 Days': '30 Days',
    'All Time': 'All Time',
    'Active Schools': 'Active Schools',
    'Total Sessions': 'Total Sessions',
    'Avg Duration': 'Avg Duration',
    'Avg Completion': 'Avg Completion',
    'School-wise Implementation Status': 'School-wise Implementation Status',
    'Sessions': 'Sessions',
    'Last Session': 'Last Session',
    'Completion': 'Completion',
    'active': 'Active',
    'stale': 'Stale',
    'inactive': 'Inactive',
    'Today': 'Today',
    'day ago': 'day ago',
    'days ago': 'days ago',
    'Never': 'Never',
    'Activity Completion Rates': 'Activity Completion Rates',
    'Which activities are teachers completing vs skipping?': 'Which activities are teachers completing vs skipping?',
    'No activity data yet': 'No activity data yet',
    'Weekly Session Frequency': 'Weekly Session Frequency',
    'Sessions per week over the last 12 weeks': 'Sessions per week over the last 12 weeks',
    'No session data yet': 'No session data yet',
    'No implementation sessions recorded yet.': 'No implementation sessions recorded yet.',
    'Teachers can log sessions from the Implementation Corner.': 'Teachers can log sessions from the Classroom Implementation.',
    'Teachers can log sessions from the Classroom Implementation.': 'Teachers can log sessions from the Classroom Implementation.',
    'P.O. / Division': 'P.O. / Division',
    'Flash Math Sprint': 'Flash Math Sprint',
    '2v2 Arithmetic Race: Solve addition and subtraction problems as fast as you can!': '2v2 Arithmetic Race: Solve addition and subtraction problems as fast as you can!',
    'Team A Zone': 'Team A Zone',
    'Team B Zone': 'Team B Zone',
    'Solve this': 'Solve this',
  },
  hi: {
    // Navbar
    'Dashboards': 'डैशबोर्ड',
    'Implementation Corner': 'कक्षा कार्यान्वयन',
    'Classroom Implementation': 'कक्षा कार्यान्वयन',
    'Back to Classroom Implementation': 'कक्षा कार्यान्वयन पर वापस जाएं',
    'Students': 'छात्र',
    'Upload': 'अपलोड',
    'Users': 'उपयोगकर्ता',
    'Data': 'डेटा',
    'Logins': 'लॉगिन',
    'Record Score': 'स्कोर दर्ज करें',
    'Sign In': 'साइन इन करें',
    'Sign Out': 'साइन आउट करें',
    // Dashboard
    'FLN Impact Dashboard': 'FLN प्रभाव डैशबोर्ड',
    'Real-time state and division progress tracking towards NIPUN Bharat Mission targets.': 'निपुण भारत मिशन लक्ष्यों की ओर वास्तविक समय राज्य और डिवीजन प्रगति ट्रैकिंग।',
    'Select Division': 'डिवीजन चुनें',
    'Select Project Office': 'परियोजना कार्यालय चुनें',
    'Select School': 'स्कूल चुनें',
    'NIPUN Bharat Mission': 'निपुण भारत मिशन',
    'The NIPUN Bharat Mission targets 100% foundational literacy and numeracy proficiency for all grade-level students. We monitor student progress through targeted baseline and endline assessments to bridge the learning gap.': 'निपुण भारत मिशन सभी ग्रेड-स्तर के छात्रों के लिए 100% बुनियादी साक्षरता और संख्यात्मकता प्रवीणता का लक्ष्य रखता है। हम सीखने के अंतर को पाटने के लिए लक्षित बेसलाइन और एंडलाइन मूल्यांकनों के माध्यम से छात्र प्रगति की निगरानी करते हैं।',
    'Literacy (L4 Story Reading)': 'साक्षरता (L4 कहानी पढ़ना)',
    'Numeracy (L3 Division)': 'संख्यात्मकता (L3 विभाजन)',
    'Current Level': 'वर्तमान स्तर',
    'Target': 'लक्ष्य',
    'Total Assessments': 'कुल मूल्यांकन',
    'Total Students': 'कुल छात्र',
    'Arena Engagement': 'अखाड़ा जुड़ाव',
    'Single Games': 'सिंगल गेम्स',
    'Target Tracking': 'लक्ष्य ट्रैकिंग',
    'Growth Velocity': 'विकास वेग',
    'Engagement Metrics': 'जुड़ाव मेट्रिक्स',
    'Pedagogy Coverage': 'शिक्षाशास्त्र कवरेज',
    'Division Rank': 'डिवीजन रैंक',
    'P.O. Rank': 'पी.ओ. रैंक',
    'Project Office Leaderboard (Endline Only)': 'परियोजना कार्यालय लीडरबोर्ड (केवल एंडलाइन)',
    'Ranking based on student story reading and subtraction mastery rates in Endline assessments.': 'एंडलाइन मूल्यांकन में छात्रों की कहानी पढ़ने और घटाव प्रवीणता दरों के आधार पर रैंकिंग।',
    'Top Performer': 'शीर्ष प्रदर्शनकर्ता',
    'Project Office': 'परियोजना कार्यालय',
    'Efficiency Score': 'दक्षता स्कोर',
    'Story Reading': 'कहानी पढ़ना',
    'Subtraction Mastery': 'घटाव प्रवीणता',
    'Assessed': 'मूल्यांकित',
    'No ranking data available for selected filters.': 'चयनित फ़िल्टर के लिए कोई रैंकिंग डेटा उपलब्ध नहीं है।',
    'Division': 'डिवीजन',
    'Proficiency': 'प्रवीणता',
    'Assessments': 'मूल्यांकन',
    'Status': 'स्थिति',
    'Growth Over Time': 'समय के साथ विकास',
    'Progress timeline showing baseline vs midline vs endline outcomes.': 'बेसलाइन बनाम मिडलाइन बनाम एंडलाइन परिणामों को दर्शाने वाली प्रगति समयरेखा।',
    'All Divisions': 'सभी डिवीजन',
    'All Project Offices': 'सभी परियोजना कार्यालय',
    'All Schools': 'सभी स्कूल',
    'All Terms': 'सभी सत्र',
    'Filters': 'फ़िल्टर',
    'Detailed Breakdown': 'विस्तृत विवरण',
    'Level': 'स्तर',
    'Showing page': 'पृष्ठ दिखा रहा है',
    'of': 'का',
    'records': 'रिकॉर्ड',
    // Students / Roster
    'Search student...': 'छात्र खोजें...',
    'Class': 'कक्षा',
    'Gender': 'लिंग',
    'Age': 'आयु',
    'School': 'स्कूल',
    'Actions': 'क्रियाएँ',
    'Add Student': 'छात्र जोड़ें',
    'No students found.': 'कोई छात्र नहीं मिला।',
    'Active Students': 'सक्रिय छात्र',
    'List of all registered students and their status.': 'सभी पंजीकृत छात्रों और उनकी स्थिति की सूची।',
    'Female': 'महिला',
    'Male': 'पुरुष',
    // Resources
    'Interactive Simulations': 'FLN खेल',
    'Hands-on simulations, games and learning pathways to master FLN concepts.': 'FLN अवधारणाओं में महारत हासिल करने के लिए व्यावहारिक सिमुलेशन, खेल और सीखने के रास्ते।',
    'Session Planner': 'सत्र योजनाकार',
    'Pedagogy Videos': 'शिक्षाशास्त्र वीडियो',
    'Articles': 'TaRL सहायता नियमावली',
    'Holistic development manuals': 'समग्र विकास नियमावली',
    'TLM Guide': 'TLM मार्गदर्शिका',
    'Maximize Learning with TLM': 'TLM के साथ सीखने को अधिकतम करें',
    'Read TLM Manual': 'TLM नियमावली पढ़ें',
    'TLM Support Videos': 'TLM सहायता वीडियो',
    'Filter by Subject': 'विषय के अनुसार फ़िल्टर करें',
    'All Subjects': 'सभी विषय',
    'Language': 'भाषा',
    'Maths': 'गणित',
    'Play Game': 'खेल खेलें',
    'Start Competition': 'प्रतियोगिता शुरू करें',
    // Levels
    'Beginner': 'शुरुआती',
    'Letter': 'अक्षर',
    'Word': 'शब्द',
    'Paragraph': 'अनुच्छेद',
    'Story': 'कहानी',
    'Num 1-9': 'अंक 1-9',
    'Num 10-99': 'संख्या 10-99',
    'Addition': 'जोड़',
    'Subtraction': 'घटाव',
    'Math Division': 'भाग',
    // Student Profile / Report Card
    'FLN Child Progress Report Card': 'FLN चाइल्ड प्रगति रिपोर्ट कार्ड',
    'Practice Games': 'अभ्यास खेल',
    'Arena Battles': 'अखाड़ा लड़ाई',
    'Total Learning Playtime': 'कुल सीखने का समय',
    'Recommended TaRL Activities': 'अनुशंसित TaRL गतिविधियाँ',
    'Literacy Focus': 'साक्षरता फोकस',
    'Numeracy Focus': 'संख्यात्मकता फोकस',
    'Assessment Audit Trail': 'मूल्यांकन ऑडिट ट्रेल',
    'Reliability Feed': 'विश्वसनीयता फ़ीड',
    'Practice Records': 'अभ्यास रिकॉर्ड',
    'Opponent': 'प्रतिद्वंद्वी',
    'Result': 'परिणाम',
    'Score': 'स्कोर',
    'Time': 'समय',
    'Draw': 'बराबरी',
    'Won 🏆': 'जीत 🏆',
    'Lost': 'हार',
    'No practice sessions logged yet.': 'अभी तक कोई अभ्यास सत्र लॉग नहीं किया गया है।',
    'No arena battles played yet.': 'अभी तक कोई अखाड़ा लड़ाई नहीं खेली गई है।',
    'Test Now': 'अभी परीक्षण करें',
    'Back to Directory': 'निर्देशिका पर वापस जाएँ',
    'Student not found.': 'छात्र नहीं मिला।',
    'No Assessments Yet': 'अभी तक कोई मूल्यांकन नहीं',
    'Test this student to generate personalized TaRL curriculum recommendations.': 'व्यक्तिगत TaRL पाठ्यक्रम अनुशंसाएँ उत्पन्न करने के लिए इस छात्र का परीक्षण करें।',
    'Literacy': 'साक्षरता',
    'Numeracy': 'संख्यात्मकता',
    'No specific activities mapped for this level yet.': 'इस स्तर के लिए अभी तक कोई विशिष्ट गतिविधियाँ मैप नहीं की गई हैं।',
    // Game Simulations
    'Math Duel (वजाबाकी आणि भागाकार)': 'गणित द्वंद्व (घटाव और भाग)',
    'Quickly solve the math problem! Speed is key to winning the point.': 'गणित की समस्या को जल्दी से हल करें! बिंदु जीतने के लिए गति महत्वपूर्ण है।',
    'Number Race (सर्वात मोठी संख्या)': 'संख्या दौड़ (सबसे बड़ी संख्या खोजें)',
    'Find the LARGEST number before your opponent does! Be the fastest to score.': 'अपने प्रतिद्वंद्वी से पहले सबसे बड़ी संख्या खोजें! स्कोर करने में सबसे तेज़ बनें।',
    'Place Value Battle (शतक-दशक-एकक)': 'स्थानिक मान युद्ध (सैकड़ा-दहाई-इकाई)',
    'Identify the total number from the H-T-O representation! First correct tap wins.': 'सैकड़ा-दहाई-इकाई प्रतिनिधित्व से कुल संख्या पहचानें! सबसे पहले सही टैप करने वाला जीतेगा।',
    'Tili Bundle Duel': 'तीली-बंडल द्वंद्व',
    'Make the number using bundles and sticks!': 'तीली और बंडल का उपयोग करके संख्या बनाएं!',
    'Bundles (Tens)': 'बंडल (दहाई)',
    'Sticks (Ones)': 'तीली (इकाई)',
    '+ Bundle': '+ बंडल',
    '+ Stick': '+ तीली',
    'Make the Number': 'संख्या बनाएं',
    'Tens': 'दहाई',
    'Ones': 'इकाई',
    // Student Leaderboard
    'Student Leaderboard': 'छात्र लीडरबोर्ड',
    'Performance Score': 'प्रदर्शन स्कोर',
    'FLN Level Score': 'FLN स्तर स्कोर',
    'Engagement Score': 'सहभागिता स्कोर',
    'Victory Bonus': 'जीत बोनस',
    'Games Played': 'खेले गए खेल',
    'Victories': 'जीतें',
    'Best Performing Students': 'सर्वश्रेष्ठ प्रदर्शन करने वाले छात्र',
    'Based on FLN levels, game participation, and battle victories': 'FLN स्तर, खेल भागीदारी और लड़ाई में जीत के आधार पर',
    'No students found matching current filters.': 'वर्तमान फ़िल्टर से मेल खाने वाले कोई छात्र नहीं मिले।',
    // TaRL Activities - Literacy
    'Sound Bingo': 'ध्वनि बिंगो',
    'Teacher says a letter sound, and students find objects in the room starting with that sound. The first to find 3 wins.': 'शिक्षक एक अक्षर की ध्वनि कहते हैं, और छात्र उस ध्वनि से शुरू होने वाली वस्तुओं को कमरे में ढूंढते हैं। सबसे पहले 3 ढूंढने वाला जीतता है।',
    'Objects in classroom': 'कक्षा की वस्तुएं',
    'Pebbles as markers': 'कंकड़',
    'Air Drawing': 'हवा में चित्रकारी',
    'Draw letters in the air using large arm movements. Have students repeat the letter\'s sound while drawing to build muscle memory.': 'हाथों के बड़े आंदोलनों का उपयोग करके हवा में अक्षर बनाएं। मांसपेशियों की याददाश्त बनाने के लिए ड्राइंग करते समय छात्रों से अक्षर की ध्वनि दोहराने को कहें।',
    'None': 'कोई नहीं',
    'Mind-Mapping Objects': 'माइंड-मैपिंग वस्तुएं',
    'Write a letter in the center of a chalkboard. Draw branches for every object students can name that starts with that letter.': 'ब्लैकबोर्ड के केंद्र में एक अक्षर लिखें। प्रत्येक वस्तु के लिए शाखाएं बनाएं जिसे छात्र उस अक्षर से शुरू होने वाले नाम दे सकें।',
    'Chalk': 'चाक',
    'Blackboard': 'ब्लैकबोर्ड',
    'Letter Sand-Trays': 'अक्षर रेत-ट्रे',
    'Provide shallow trays of sand or dirt. Have students trace letters they recognize. This tactile feedback is essential for recall.': 'रेत या मिट्टी की उथली ट्रे प्रदान करें। छात्रों से उन अक्षरों का पता लगाने को कहें जिन्हें वे पहचानते हैं। यह स्पर्श प्रतिक्रिया याद रखने के लिए आवश्यक है।',
    'Sand/Dirt': 'रेत/मिट्टी',
    'Shallow trays': 'उथली ट्रे',
    'Read-Around-the-Circle': 'चक्र में पढ़ना',
    'Sit in a circle. Each student reads one basic word from a flashcard. If they get it right, they stay in; otherwise, they get a \'bonus\' word.': 'एक घेरे में बैठें। प्रत्येक छात्र फ्लैशकार्ड से एक बुनियादी शब्द पढ़ता है। यदि वे इसे सही पाते हैं, तो वे बने रहते हैं; अन्यथा, उन्हें एक \'बोनस\' शब्द मिलता है।',
    'Word Flashcards': 'शब्द फ्लैशकार्ड',
    'Word Building Blocks': 'शब्द निर्माण ब्लॉक',
    'Use individual letter tiles (C-A-T). Have students physically move tiles to form new words like B-A-T or M-A-T.': 'व्यक्तिगत अक्षर टाइल्स का उपयोग करें। छात्रों से शारीरिक रूप से टाइल्स को स्थानांतरित करने के लिए कहें ताकि नए शब्द बन सकें।',
    'Letter tiles': 'अक्षर टाइल्स',
    'Stop-and-Predict': 'रुकें और अनुमान लगाएं',
    'Read a paragraph aloud. Stop halfway and ask the student what they think will happen next to build active comprehension.': 'एक पैराग्राफ जोर से पढ़ें। बीच में रुकें और छात्र से पूछें कि वे क्या सोचते हैं कि आगे क्या होगा ताकि सक्रिय समझ का निर्माण हो सके।',
    'Storybooks': 'कहानी की किताबें',
    'Paragraph cards': 'पैराग्राफ कार्ड',
    'Sentence Jumble': 'वाक्य जंबल',
    'Write sentences from a paragraph on separate strips. Have the student arrange them in the correct sequential order.': 'एक पैराग्राफ से वाक्यों को अलग-अलग पट्टियों पर लिखें। छात्र से उन्हें सही अनुक्रमिक क्रम में व्यवस्थित करने को कहें।',
    'Paper strips': 'कागज की पट्टियाँ',
    'Scissors': 'कैंची',
    'Moral Summaries': 'नैतिक सारांश',
    'After reading a story, ask the student to write one \'moral\' or lesson they learned in their own words.': 'एक कहानी पढ़ने के बाद, छात्र से अपने शब्दों में एक सीख या सबक लिखने को कहें जो उन्होंने सीखा।',
    'Notebook': 'नोटबुक',
    'Pencil': 'पेंसिल',
    'Roleplay Theater': 'रोलप्ले थिएटर',
    'Choose a story character and have the student act out their favorite scene. This deepens emotional connection to the text.': 'एक कहानी चरित्र चुनें और छात्र से उनके पसंदीदा दृश्य का अभिनय करने को कहें। यह पाठ के साथ भावनात्मक संबंध को गहरा करता है।',
    'Basic props': 'बुनियादी प्रॉप्स',
    // TaRL Activities - Numeracy
    'Number Songs': 'संख्या गीत',
    'Sing \'Five Little Ducks\' or similar counting songs while using fingers to physically subtract numbers.': 'उंगलियों का उपयोग करके संख्या घटाते हुए \'पांच बत्तखें\' या इसी तरह के गिनती के गाने गाएं।',
    'Rock Counting': 'चट्टान गिनती',
    'Gather 10 stones. Count them one by one, moving them from a \'pile\' to a \'line\'. Ask \'How many now?\' frequently.': '10 पत्थर इकट्ठा करें। उन्हें एक-एक करके गिनें, उन्हें एक \'ढेर\' से \'लाइन\' में ले जाएं। बार-बार पूछें \'अब कितने हैं?\'',
    'Stones/Seeds': 'पत्थर/बीज',
    'Dot Matching': 'बिंदु मिलान',
    'On a sheet of paper, draw groups of dots next to numbers. Have the student draw lines connecting the correct pairs.': 'कागज की एक शीट पर, संख्याओं के बगल में बिंदुओं के समूह बनाएं। छात्र से सही जोड़े जोड़ने वाली रेखाएं खींचने को कहें।',
    'Paper': 'कागज',
    'Marker': 'मार्कर',
    'Flashcard Hopscotch': 'फ्लैशकार्ड हॉपस्कॉच',
    'Draw hopscotch grids with numbers 1-9. The child must say the number aloud before jumping into the square.': '1-9 संख्याओं के साथ हॉपस्कॉच ग्रिड बनाएं। बच्चे को वर्ग में कूदने से पहले जोर से संख्या कहनी होगी।',
    'Outdoor space': 'बाहरी स्थान',
    'Bundle Races': 'बंडल दौड़',
    'Give students 30 sticks. Whoever ties them into 3 bundles of 10 the fastest wins. Teaches the concept of \'tens\'.': 'छात्रों को 30 लकड़ियाँ दें। जो भी उन्हें सबसे तेजी से 10 के 3 बंडलों में बांधता है वह जीतता है। यह \'दहाई\' की अवधारणा सिखाता है।',
    'Sticks/Straws': 'लकड़ियाँ/स्ट्रॉ',
    'Rubber bands': 'रबर बैंड',
    'Place Value Grids': 'स्थानीय मान ग्रिड',
    'Use an abacus or a drawn H-T-U (Hundreds, Tens, Units) grid. Have students place pebbles in each column to represent 562.': 'एक एबाकस या खींचे गए H-T-U (सैकड़ा, दहाई, इकाई) ग्रिड का उपयोग करें। छात्रों से 562 का प्रतिनिधित्व करने के लिए प्रत्येक कॉलम में कंकड़ रखने को कहें।',
    'H-T-U Grid': 'H-T-U ग्रिड',
    'Pebbles': 'कंकड़',
    'Carry-over Grids': 'हासिल ग्रिड',
    'Use a color-coded carry-over grid. When adding 9+5, show how the \'1\' jumps into the Tens column visually.': 'एक रंग-कोडित हासिल ग्रिड का उपयोग करें। जब 9+5 जोड़ते हैं, तो दिखाएं कि \'1\' कैसे दहाई कॉलम में कूदता है।',
    'Color markers': 'रंग मार्कर',
    'Grid paper': 'ग्रिड पेपर',
    'Borrowing Roleplay': 'उधार लेने का अभिनय',
    'Roleplay \'Borrowing a Bundle\'. If I have 2 bundles and 3 sticks, and I need to give away 5, I must \'untie\' one bundle.': '\'बंडल उधार लेने\' का अभिनय करें। यदि मेरे पास 2 बंडल और 3 लकड़ियाँ हैं, और मुझे 5 देने हैं, तो मुझे एक बंडल \'खोलना\' होगा।',
    'Bundles of 10': '10 के बंडल',
    'Loose sticks': 'खुली लकड़ियाँ',
    'Fair Share Picnic': 'निष्पक्ष साझा पिकनिक',
    'Give a student 20 seeds and 4 friends. Ask them to distribute the seeds \'fairly\' so everyone has an equal amount.': 'एक छात्र को 20 बीज और 4 मित्र दें। उनसे बीजों को \'समान रूप से\' वितरित करने के लिए कहें ताकि सभी के पास समान मात्रा हो।',
    'Seeds': 'बीज',
    'Plates/Cups': 'प्लेट/कप',
    // Implementation Tracker
    'Implementation Tracker': 'कार्यान्वयन ट्रैकर',
    'Track school-wise 90-minute cycle implementation and activity completion.': 'स्कूल-वार 90-मिनट चक्र कार्यान्वयन और गतिविधि पूर्णता को ट्रैक करें।',
    '7 Days': '7 दिन',
    '30 Days': '30 दिन',
    'All Time': 'संपूर्ण समय',
    'Active Schools': 'सक्रिय स्कूल',
    'Total Sessions': 'कुल सत्र',
    'Avg Duration': 'औसत अवधि',
    'Avg Completion': 'औसत पूर्णता',
    'School-wise Implementation Status': 'स्कूल-वार कार्यान्वयन स्थिति',
    'Sessions': 'सत्र',
    'Last Session': 'अंतिम सत्र',
    'Completion': 'पूर्णता',
    'active': 'सक्रिय',
    'stale': 'अचल',
    'inactive': 'निष्क्रिय',
    'Today': 'आज',
    'day ago': 'दिन पहले',
    'days ago': 'दिन पहले',
    'Never': 'कभी नहीं',
    'Activity Completion Rates': 'गतिविधि पूर्णता दर',
    'Which activities are teachers completing vs skipping?': 'शिक्षक कौन सी गतिविधियाँ पूरी कर रहे हैं और कौन सी छोड़ रहे हैं?',
    'No activity data yet': 'अभी तक कोई गतिविधि डेटा नहीं',
    'Weekly Session Frequency': 'साप्ताहिक सत्र आवृत्ति',
    'Sessions per week over the last 12 weeks': 'पिछले 12 सप्ताह में प्रति सप्ताह सत्र',
    'No session data yet': 'अभी तक कोई सत्र डेटा नहीं',
    'No implementation sessions recorded yet.': 'अभी तक कोई कार्यान्वयन सत्र रिकॉर्ड नहीं किया गया।',
    'Teachers can log sessions from the Implementation Corner.': 'शिक्षक कक्षा कार्यान्वयन से सत्र लॉग कर सकते हैं।',
    'Teachers can log sessions from the Classroom Implementation.': 'शिक्षक कक्षा कार्यान्वयन से सत्र लॉग कर सकते हैं।',
    'P.O. / Division': 'प.का. / विभाग',
    'Flash Math Sprint': 'फ़्लैश मैथ स्प्रिंट',
    '2v2 Arithmetic Race: Solve addition and subtraction problems as fast as you can!': '2v2 Arithmetic Race: जोड़ और घटाव की समस्याओं को जितनी जल्दी हो सके हल करें!',
    'Team A Zone': 'टीम A ज़ोन',
    'Team B Zone': 'टीम B ज़ोन',
    'Solve this': 'इसे हल करें',
  },
  mr: {
    // Navbar
    'Dashboards': 'डॅशबोर्ड',
    'Implementation Corner': 'वर्ग अंमलबजावणी',
    'Classroom Implementation': 'वर्ग अंमलबजावणी',
    'Back to Classroom Implementation': 'वर्ग अंमलबजावणीवर परत जा',
    'Students': 'विद्यार्थी',
    'Upload': 'अपलोड',
    'Users': 'वापरकर्ते',
    'Data': 'माहिती',
    'Logins': 'लॉगिन',
    'Record Score': 'गुण नोंदवा',
    'Sign In': 'लॉग इन करा',
    'Sign Out': 'बाहेर पडा',
    // Dashboard
    'FLN Impact Dashboard': 'FLN प्रभाव डॅशबोर्ड',
    'Real-time state and division progress tracking towards NIPUN Bharat Mission targets.': 'निपुण भारत मिशन लक्ष्यांच्या देशाने रिअल-टाइम राज्य आणि विभाग प्रगती ट्रॅकिंग.',
    'Select Division': 'विभाग निवडा',
    'Select Project Office': 'प्रकल्प कार्यालय निवडा',
    'Select School': 'शाळा निवडा',
    'NIPUN Bharat Mission': 'निपुण भारत मिशन',
    'The NIPUN Bharat Mission targets 100% foundational literacy and numeracy proficiency for all grade-level students. We monitor student progress through targeted baseline and endline assessments to bridge the learning gap.': 'निपुण भारत मिशन सर्व इयत्तेच्या विद्यार्थ्यांसाठी १००% पायाभूत साक्षरता आणि संख्याज्ञान प्राविण्य लक्ष्य ठेवते. आम्ही शिकण्यातील अंतर भरून काढण्यासाठी लक्ष्यित बेसलाइन आणि एंडलाइन मूल्यमापनांद्वारे विद्यार्थ्यांच्या प्रगतीचे निरीक्षण करतो.',
    'Literacy (L4 Story Reading)': 'साक्षरता (L4 कथा वाचन)',
    'Numeracy (L3 Division)': 'संख्याज्ञान (L3 भागाकार)',
    'Current Level': 'सध्याची पातळी',
    'Target': 'लक्ष्य',
    'Total Assessments': 'एकूण मूल्यमापने',
    'Total Students': 'एकूण विद्यार्थी',
    'Arena Engagement': 'आखाडा सहभाग',
    'Single Games': 'सिंगल गेम्स',
    'Target Tracking': 'लक्ष्य ट्रॅकिंग',
    'Growth Velocity': 'वाढ वेग',
    'Engagement Metrics': 'सहभाग मेट्रिक्स',
    'Pedagogy Coverage': 'शिक्षणशास्त्र व्याप्ती',
    'Division Rank': 'विभाग रँक',
    'P.O. Rank': 'पी.ओ. रँक',
    'Project Office Leaderboard (Endline Only)': 'प्रकल्प कार्यालय लीडरबोर्ड (फक्त एंडलाइन)',
    'Ranking based on student story reading and subtraction mastery rates in Endline assessments.': 'एंडलाइन मूल्यांकनात विद्यार्थ्यांच्या गोष्ट वाचन आणि वजाबाकी प्रवीणता दरांवर आधारित क्रमवारी.',
    'Top Performer': 'उत्कृष्ट कामगिरी करणारा',
    'Project Office': 'प्रकल्प कार्यालय',
    'Efficiency Score': 'दक्षता स्कोर',
    'Story Reading': 'गोष्ट वाचन',
    'Subtraction Mastery': 'वजाबाकी प्रवीणता',
    'Assessed': 'मूल्यांकन केलेले',
    'No ranking data available for selected filters.': 'निवडलेल्या फिल्टरसाठी कोणतीही क्रमवारी उपलब्ध नाही।',
    'Division': 'विभाग',
    'Proficiency': 'प्राविण्य',
    'Assessments': 'मूल्यमापने',
    'Status': 'स्थिती',
    'Growth Over Time': 'काळानुसार वाढ',
    'Progress timeline showing baseline vs midline vs endline outcomes.': 'बेसलाइन विरुद्ध मिडलाइन विरुद्ध एंडलाइन परिणाम दर्शवणारी प्रगती टाइमलाइन.',
    'All Divisions': 'सर्व विभाग',
    'All Project Offices': 'सर्व प्रकल्प कार्यालये',
    'All Schools': 'सर्व शाळा',
    'All Terms': 'सर्व सत्र',
    'Filters': 'फिल्टर्स',
    'Detailed Breakdown': 'तपशीलवार वर्गीकरण',
    'Level': 'पातळी',
    'Showing page': 'पृष्ठ दर्शवत आहे',
    'of': 'पैकी',
    'records': 'नोंदी',
    // Students / Roster
    'Search student...': 'विद्यार्थी शोधा...',
    'Class': 'इयत्ता',
    'Gender': 'लिंग',
    'Age': 'वय',
    'School': 'शाळा',
    'Actions': 'कृती',
    'Add Student': 'विद्यार्थी joडा',
    'No students found.': 'कोणतेही विद्यार्थी आढळले नाहीत.',
    'Active Students': 'सक्रिय विद्यार्थी',
    'List of all registered students and their status.': 'सर्व नोंदणीकृत विद्यार्थ्यांची आणि त्यांच्या स्थितीची सूची.',
    'Female': 'स्त्री',
    'Male': 'पुरुष',
    // Resources
    'Interactive Simulations': 'FLN खेळ',
    'Hands-on simulations, games and learning pathways to master FLN concepts.': 'FLN संकल्पनांवर प्रभुत्व मिळविण्यासाठी हँड्स-ऑन सिम्युलेशन, खेळ आणि शिकण्याचे मार्ग.',
    'Session Planner': 'सत्र नियोजक',
    'Pedagogy Videos': 'अध्यापनशास्त्र व्हिडिओ',
    'Articles': 'TaRL मदत पुस्तिका',
    'Holistic development manuals': 'सर्वसमावेशक विकास पुस्तिका',
    'TLM Guide': 'TLM मार्गदर्शिका',
    'Maximize Learning with TLM': 'TLM सह शिक्षण जास्तीत जास्त वाढवा',
    'Read TLM Manual': 'TLM पुस्तिका वाचा',
    'TLM Support Videos': 'TLM मदत व्हिडिओ',
    'Filter by Subject': 'विषयानुसार फिल्टर करा',
    'All Subjects': 'सर्व विषय',
    'Language': 'भाषा',
    'Maths': 'गणित',
    'Play Game': 'खेळ खेळा',
    'Start Competition': 'स्पर्धा सुरू करा',
    // Levels
    'Beginner': 'सुरुवातीची',
    'Letter': 'अक्षर',
    'Word': 'शब्द',
    'Paragraph': 'परिच्छेद',
    'Story': 'गोष्ट',
    'Num 1-9': 'अंक १-९',
    'Num 10-99': 'संख्या १०-९९',
    'Addition': 'बेरीज',
    'Subtraction': 'वजाबाकी',
    'Math Division': 'भागाकार',
    // Student Profile / Report Card
    'FLN Child Progress Report Card': 'FLN बाल प्रगती अहवाल पत्रक',
    'Practice Games': 'सराव खेळ',
    'Arena Battles': 'आखाडा लढती',
    'Total Learning Playtime': 'एकूण शिकण्याची वेळ',
    'Recommended TaRL Activities': 'शिफारस केलेल्या TaRL कृती',
    'Literacy Focus': 'साक्षरता लक्ष',
    'Numeracy Focus': 'संख्याज्ञान लक्ष',
    'Assessment Audit Trail': 'मूल्यमापन इतिहास',
    'Reliability Feed': 'विश्वासार्हता प्रवाह',
    'Practice Records': 'सराव नोंदी',
    'Opponent': 'प्रतिस्पर्धी',
    'Result': 'निकाल',
    'Score': 'गुण',
    'Time': 'वेळ',
    'Draw': 'सामना अनिर्णित',
    'Won 🏆': 'विजयी 🏆',
    'Lost': 'पराभूत',
    'No practice sessions logged yet.': 'अद्याप कोणताही सराव खेळ खेळलेला नाही.',
    'No arena battles played yet.': 'अद्याप एकही आखाडा लढत खेळलेली नाही.',
    'Test Now': 'आता मूल्यमापन करा',
    'Back to Directory': 'यादीवर परत जा',
    'Student not found.': 'विद्यार्थी आढळला नाही.',
    'No Assessments Yet': 'अद्याप कोणतेही मूल्यमापन नाही',
    'Test this student to generate personalized TaRL curriculum recommendations.': 'वैयक्तिकृत TaRL अभ्यासक्रम शिफारसी मिळवण्यासाठी या विद्यार्थ्याचे मूल्यमापन करा.',
    'Literacy': 'साक्षरता',
    'Numeracy': 'संख्याज्ञान',
    'No specific activities mapped for this level yet.': 'या पातळीसाठी अद्याप कोणतीही विशिष्ट कृती निश्चित केलेली नाही.',
    // Game Simulations
    'Math Duel (वजाबाकी आणि भागाकार)': 'गणित द्वंद्व (वजाबाकी आणि भागाकार)',
    'Quickly solve the math problem! Speed is key to winning the point.': 'गणिताचे कोडे पटकन सोडवा! गुण मिळवण्यासाठी वेग महत्त्वाचा आहे।',
    'Number Race (सर्वात मोठी संख्या)': 'संख्या शर्यत (सर्वात मोठी संख्या)',
    'Find the LARGEST number before your opponent does! Be the fastest to score.': 'तुमच्या प्रतिस्पर्ध्याच्या आधी सर्वात मोठी संख्या शोधा! वेगाने गुण मिळवा।',
    'Place Value Battle (शतक-दशक-एकक)': 'स्थानिक किंमत द्वंद्व (शतक-दशक-एकक)',
    'Identify the total number from the H-T-O representation! First correct tap wins.': 'शतक-दशक-एकक स्वरूपावरून एकूण संख्या ओळखा! आधी अचूक उत्तर देणारा जिंकेल।',
    'Tili Bundle Duel': 'टिली-बंडल द्वंद्व',
    'Make the number using bundles and sticks!': 'टिली आणि काड्या वापरून संख्या बनवा!',
    'Bundles (Tens)': 'टिली (दहे)',
    'Sticks (Ones)': 'काड्या (एकके)',
    '+ Bundle': '+ टिली',
    '+ Stick': '+ काडी',
    'Make the Number': 'संख्या बनवा',
    'Tens': 'दहे',
    'Ones': 'एकके',
    // Student Leaderboard
    'Student Leaderboard': 'विद्यार्थी लीडरबोर्ड',
    'Performance Score': 'प्रदर्शन गुण',
    'FLN Level Score': 'FLN पातळी गुण',
    'Engagement Score': 'सहभागिता गुण',
    'Victory Bonus': 'विजय बोनस',
    'Games Played': 'खेळलेले खेळ',
    'Victories': 'विजय',
    'Best Performing Students': 'सर्वोत्कृष्ट कामगिरी करणारे विद्यार्थी',
    'Based on FLN levels, game participation, and battle victories': 'FLN पातळी, खेळ सहभाग आणि आखाडा विजयांवर आधारित',
    'No students found matching current filters.': 'निवडलेल्या फिल्टरनुसार कोणतेही विद्यार्थी आढळले नाहीत.',
    // TaRL Activities - Literacy
    'Sound Bingo': 'ध्वनी बिंगो',
    'Teacher says a letter sound, and students find objects in the room starting with that sound. The first to find 3 wins.': 'शिक्षकाने अक्षराचा आवाज सांगावा आणि विद्यार्थ्यांनी त्या आवाजापासून सुरू होणाऱ्या वस्तू खोलीत शोधाव्यात. पहिले ३ शोधणारा जिंकेल.',
    'Objects in classroom': 'वर्गातील वस्तू',
    'Pebbles as markers': 'खडे',
    'Air Drawing': 'हवेत चित्र काढणे',
    'Draw letters in the air using large arm movements. Have students repeat the letter\'s sound while drawing to build muscle memory.': 'हात हलवून हवेत अक्षरे काढा. स्नायूंची स्मरणशक्ती मजबूत करण्यासाठी रेखाटन करताना विद्यार्थ्यांनी अक्षराचा उच्चार पुनरावृत्ती करावा.',
    'None': 'काहीही नाही',
    'Mind-Mapping Objects': 'माइंड-मॅपिंग वस्तू',
    'Write a letter in the center of a chalkboard. Draw branches for every object students can name that starts with that letter.': 'फळ्याच्या मध्यभागी एक अक्षर लिहा. विद्यार्थी त्या अक्षरापासून सुरू होणाऱ्या ज्या वस्तूंचे नाव सांगतील, त्यांच्यासाठी रेषा ओढा.',
    'Chalk': 'खडू',
    'Blackboard': 'फळा',
    'Letter Sand-Trays': 'अक्षर रेती-ट्रे',
    'Provide shallow trays of sand or dirt. Have students trace letters they recognize. This tactile feedback is essential for recall.': 'रेती किंवा मातीने भरलेल्या उथळ्या ट्रे द्या. विद्यार्थ्यांनी ओळखलेले अक्षरे त्यावर गिरवू द्या. ही स्पर्श संवेदना लक्षात ठेवण्यासाठी आवश्यक आहे.',
    'Sand/Dirt': 'रेती/माती',
    'Shallow trays': 'उथळ ट्रे',
    'Read-Around-the-Circle': 'वर्तुळात वाचन',
    'Sit in a circle. Each student reads one basic word from a flashcard. If they get it right, they stay in; otherwise, they get a \'bonus\' word.': 'वर्तुळात बसा. प्रत्येक विद्यार्थी फ्लॅशकार्डवरील एक साधा शब्द वाचतो. बरोबर वाचल्यास ते खेळात राहतील; अन्यथा त्यांना एक अतिरिक्त शब्द दिला जाईल.',
    'Word Flashcards': 'शब्द फ्लॅशकार्ड',
    'Word Building Blocks': 'शब्द जोडणी ब्लॉक्स',
    'Use individual letter tiles (C-A-T). Have students physically move tiles to form new words like B-A-T or M-A-T.': 'अक्षरांच्या सुट्या पाट्या वापरा. विद्यार्थ्यांनी पाट्या हलवून नवीन शब्द बनवावे.',
    'Letter tiles': 'अक्षरांच्या पाट्या',
    'Stop-and-Predict': 'थांबा आणि अंदाज लावा',
    'Read a paragraph aloud. Stop halfway and ask the student what they think will happen next to build active comprehension.': 'एक परिच्छेद मोठ्याने वाचा. अर्ध्यात थांबा आणि आकलन क्षमता वाढवण्यासाठी पुढे काय होईल असे वाटते ते विद्यार्थ्याला विचारा.',
    'Storybooks': 'कथांची पुस्तके',
    'Paragraph cards': 'परिच्छेद कार्ड',
    'Sentence Jumble': 'वाक्य जुळवाजुळव',
    'Write sentences from a paragraph on separate strips. Have the student arrange them in the correct sequential order.': 'परिच्छेदातील वाक्ये वेगवेगळ्या पट्ट्यांवर लिहा. विद्यार्थ्याला ती योग्य क्रमाने मांडण्यास सांगा.',
    'Paper strips': 'कागदाच्या पट्ट्या',
    'Scissors': 'कात्री',
    'Moral Summaries': 'तात्पर्य सारांश',
    'After reading a story, ask the student to write one \'moral\' or lesson they learned in their own words.': 'गोष्ट वाचल्यानंतर, विद्यार्थ्यांनी स्वतःच्या शब्दांत त्यांना मिळालेला बोध किंवा धडा लिहिण्यास सांगा.',
    'Notebook': 'वही/नोटबुक',
    'Pencil': 'पेन्सिल',
    'Roleplay Theater': 'भूमिका अभिनय',
    'Choose a story character and have the student act out their favorite scene. This deepens emotional connection to the text.': 'गोष्टीतील एखादे पात्र निवडा आणि विद्यार्थ्याला त्याचा आवडता प्रसंग अभिनय करून दाखवायला सांगा. यामुळे गोष्टीशी भावनिक नाते जोडले जाते.',
    'Basic props': 'साधे साहित्य/प्रॉप्स',
    // TaRL Activities - Numeracy
    'Number Songs': 'संख्यांचे गाणे',
    'Sing \'Five Little Ducks\' or similar counting songs while using fingers to physically subtract numbers.': 'बोटांचा वापर करून संख्या वजा करत \'पाच बदके\' किंवा तत्सम मोजणीची गाणी म्हणा.',
    'Rock Counting': 'दगड मोजणे',
    'Gather 10 stones. Count them one by one, moving them from a \'pile\' to a \'line\'. Ask \'How many now?\' frequently.': '१० दगड गोळा करा. एक-एक करून मोजा आणि त्यांना ढिगाऱ्यातून ओळीत ठेवा. वारंवार विचारा \'आता किती झाले?\'',
    'Stones/Seeds': 'दगड/बिया',
    'Dot Matching': 'ठिपके जोडणे',
    'On a sheet of paper, draw groups of dots next to numbers. Have the student draw lines connecting the correct pairs.': 'कागदावर संख्यांच्या बाजूला ठिपके काढा. विद्यार्थ्याला योग्य जोड्या जोडणाऱ्या रेषा काढण्यास सांगा.',
    'Paper': 'कागद',
    'Marker': 'पेन/मार्कर',
    'Flashcard Hopscotch': 'फ्लॅशकार्ड लंगडी',
    'Draw hopscotch grids with numbers 1-9. The child must say the number aloud before jumping into the square.': '१-९ संख्या असलेली लंगडीची चौकट आखा. चौकटीत उडी मारण्यापूर्वी मुलाने संख्या मोठ्याने उच्चारली पाहिजे.',
    'Outdoor space': 'मैदान/बाहेरची जागा',
    'Bundle Races': 'बंडल शर्यत',
    'Give students 30 sticks. Whoever ties them into 3 bundles of 10 the fastest wins. Teaches the concept of \'tens\'.': 'विद्यार्थ्यांना ३० काड्या द्या. जो सर्वात जलद १० चे ३ बंडल बांधेल तो जिंकेल. यामुळे \'दशक\' संकल्पना समजते.',
    'Sticks/Straws': 'काड्या/स्ट्रॉ',
    'Rubber bands': 'रबर बँड',
    'Place Value Grids': 'स्थानिक किंमत तक्ता',
    'Use an abacus or a drawn H-T-U (Hundreds, Tens, Units) grid. Have students place pebbles in each column to represent 562.': 'मणीपट्टी (Abacus) किंवा रेखाटलेला शतक-दशक-एकक तक्ता वापरा. ५६२ संख्या दाखवण्यासाठी विद्यार्थ्यांनी प्रत्येक रकान्यात खडे ठेवावेत.',
    'H-T-U Grid': 'शतक-दशक-एकक तक्ता',
    'Pebbles': 'खडे',
    'Carry-over Grids': 'हातच्याची बेरीज तक्ता',
    'Use a color-coded carry-over grid. When adding 9+5, show how the \'1\' jumps into the Tens column visually.': 'रंगीत हातच्याचा तक्ता वापरा. ९+५ जोडताना \'१\' दशक रकान्यात कसा जातो ते स्पष्ट करा.',
    'Color markers': 'रंगीत पेन',
    'Grid paper': 'आलेख/चौकटीचा कागद',
    'Borrowing Roleplay': 'हातचा वजाबाकी अभिनय',
    'Roleplay \'Borrowing a Bundle\'. If I have 2 bundles and 3 sticks, and I need to give away 5, I must \'untie\' one bundle.': '\'दशकाचे बंडल सोडणे\' असा अभिनय करा. माझ्याकडे २ बंडल आणि ३ काड्या आहेत आणि मला ५ द्यायचे असल्यास, मला एक बंडल सोडावे लागेल.',
    'Bundles of 10': '१० चे बंडल',
    'Loose sticks': 'सुट्या काड्या',
    'Fair Share Picnic': 'समान वाटप खेळ',
    'Give a student 20 seeds and 4 friends. Ask them to distribute the seeds \'fairly\' so everyone has an equal amount.': 'विद्यार्थ्याला २० बिया आणि ४ मित्र द्या. बियांचे सर्वांना समान वाटप करण्यास सांगा जेणेकरून प्रत्येकाला समान भाग मिळेल.',
    'Seeds': 'बिया',
    'Plates/Cups': 'प्लेट/कप',
    // Implementation Tracker
    'Implementation Tracker': 'अंमलबजावणी ट्रॅकर',
    'Track school-wise 90-minute cycle implementation and activity completion.': 'शाळानिहाय ९०-मिनिट चक्र अंमलबजावणी आणि कृती पूर्णता ट्रॅक करा.',
    '7 Days': '७ दिवस',
    '30 Days': '३० दिवस',
    'All Time': 'संपूर्ण काळ',
    'Active Schools': 'सक्रिय शाळा',
    'Total Sessions': 'एकूण सत्रे',
    'Avg Duration': 'सरासरी कालावधी',
    'Avg Completion': 'सरासरी पूर्णता',
    'School-wise Implementation Status': 'शाळानिहाय अंमलबजावणी स्थिती',
    'Sessions': 'सत्रे',
    'Last Session': 'शेवटचे सत्र',
    'Completion': 'पूर्णता',
    'active': 'सक्रिय',
    'stale': 'शिळा',
    'inactive': 'निष्क्रिय',
    'Today': 'आज',
    'day ago': 'दिवसापूर्वी',
    'days ago': 'दिवसांपूर्वी',
    'Never': 'कधीच नाही',
    'Activity Completion Rates': 'कृती पूर्णता दर',
    'Which activities are teachers completing vs skipping?': 'शिक्षक कोणत्या कृती पूर्ण करत आहेत आणि कोणत्या सोडत आहेत?',
    'No activity data yet': 'अजून कृती डेटा नाही',
    'Weekly Session Frequency': 'साप्ताहिक सत्र वारंवारता',
    'Sessions per week over the last 12 weeks': 'गेल्या १२ आठवड्यांत प्रति आठवडा सत्रे',
    'No session data yet': 'अजून सत्र डेटा नाही',
    'No implementation sessions recorded yet.': 'अजून कोणतेही अंमलबजावणी सत्र नोंदवलेले नाही.',
    'Teachers can log sessions from the Implementation Corner.': 'शिक्षक वर्ग अंमलबजावणीतून सत्रे नोंदवू शकतात.',
    'Teachers can log sessions from the Classroom Implementation.': 'शिक्षक वर्ग अंमलबजावणीतून सत्रे नोंदवू शकतात.',
    'P.O. / Division': 'प.का. / विभाग',
    'Flash Math Sprint': 'फ्लॅश मॅथ स्प्रिंट',
    '2v2 Arithmetic Race: Solve addition and subtraction problems as fast as you can!': '2v2 Arithmetic शर्यत: बेरीज आणि वजाबाकीची गणिते शक्य तितक्या लवकर सोडवा!',
    'Team A Zone': 'टीम A झोन',
    'Team B Zone': 'टीम B झोन',
    'Solve this': 'हे सोडवा',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && (saved === 'en' || saved === 'hi' || saved === 'mr')) {
      setLanguageState(saved);
      document.cookie = `app-language=${saved}; path=/; max-age=31536000; SameSite=Lax`;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    document.cookie = `app-language=${lang}; path=/; max-age=31536000; SameSite=Lax`;
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? key;
  };

  const tNum = (num: number | string): string => {
    if (language === 'mr') {
      const devanagariDigits = ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'];
      return String(num).replace(/[0-9]/g, (w) => devanagariDigits[+w]);
    }
    return String(num);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tNum }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
